server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # This section scrapes logs from other Docker containers
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # We only want to scrape containers with the label "logging=true"
      - source_labels: [__meta_docker_container_label_logging]
        regex: "true"
        action: keep
      # This sets a 'job' label in Loki based on the container name
      - source_labels: [__meta_docker_container_name]
        regex: "/(.*)"
        target_label: "job"